# -*- coding: utf-8 -*-
"""Previsão de Indicadores Fisiológicos em Atletas com Scikit-Learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOQLcUEiS-9IP9pqFuNGKMtdKLYI8nk0

##Previsão de Indicadores Fisiológicos em Atletas com Scikit-Learn

Neste projeto, analiso como o desempenho físico (exercícios de força e explosão) impacta os indicadores fisiológicos de atletas. Esse tipo de modelagem é a base para algoritmos de Load Management (gestão de carga), usados para evitar o overtraining e, consequentemente, reduzir o risco de lesões.
"""

from sklearn.datasets import load_linnerud
import pandas as pd

# Carregando o dataset
linnerud = load_linnerud()

# Transformando em DataFrames para facilitar a visualização
df_exercicios = pd.DataFrame(linnerud.data, columns=linnerud.feature_names)
df_fisiologia = pd.DataFrame(linnerud.target, columns=linnerud.target_names)

# Unindo para ver a correlação completa
df_completo = pd.concat([df_exercicios, df_fisiologia], axis=1)

print(df_completo.head())

"""Correlação: Quem faz mais exercício tem o coração mais acostumado?
Podemos notar uma correlação negativa entre o número de abdominais (Situps) e a pulsação (Pulse)

Com isso, é possível afirmar que os atletas com maior resistência muscular tendem a ter uma frequência cardíaca basal menor, o que é um indicador de melhor condicionamento e menor risco de fadiga (um precursor de lesões).

Vamos tornar isso mais visual:
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Configurando o estilo dos gráficos
sns.set_theme(style="whitegrid")

# 1. Mapa de Calor (Correlação)
plt.figure(figsize=(6, 3))
sns.heatmap(df_completo.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Mapa de Calor: Entendendo a relação entre Exercício e Fisiologia')
plt.show()

# 2. Relação entre Abdominais e Cintura (Exemplo de insight de saúde)
plt.figure(figsize=(6, 3))
sns.regplot(data=df_completo, x='Situps', y='Waist', color='teal')
plt.title('Relação: Abdominais vs Medida da Cintura')
plt.xlabel('Número de Abdominais')
plt.ylabel('Medida da Cintura')
plt.show()

# 3. Distribuição da Pulsação (Para ver se os atletas são homogêneos)
plt.figure(figsize=(6, 3))
sns.histplot(df_completo['Pulse'], kde=True, color='salmon')
plt.title('Distribuição da Frequência Cardíaca (Pulse)')
plt.show()

"""Durante a análise exploratória, identifiquei uma colinearidade forte ($0,87$) entre o peso e a medida da cintura dos atletas. Para o modelo de machine learning, isso é um ponto de atenção: variáveis muito correlacionadas podem fornecer informações redundantes

Já a relação entre Situps (Abdominais) e Waist (Cintura), mostra um número negativo (Em torno de $-0,6$) o que significa que quanto mais abdominais o atleta faz, menor tende a ser a cintura. Isso reforça a conexão entre a performance de força do corpo e os indicadores de composição física.

Agora que entendemos os dados, vamos para o modelo de Machine Learning. Como o dataset é pequeno, o ideal é usarmos uma Regressão Linear.

Vamos tentar prever o Peso (Weight) do atleta baseando-se na performance dele nos exercícios. Isso é útil para entender se a performance atual condiz com a categoria de peso do atleta.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Definindo as variáveis
X = df_exercicios # Nossas "features" (Chins, Situps, Jumps)
y = df_fisiologia['Weight'] # Nosso "target" (Peso)

# 2. Dividindo em Treino (80%) e Teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Treinaremos com {len(X_train)} amostras e testaremos com {len(X_test)}.")

# 1. Criar o modelo
modelo = LinearRegression()

# 2. Treinar o modelo (O "aluno" estuda os dados de treino)
modelo.fit(X_train, y_train)

# 3. Fazer Predições (O "aluno" faz a prova com os dados de teste)
y_pred = modelo.predict(X_test)

# 4. Avaliar o desempenho
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Erro Médio Absoluto (MAE): {mae:.2f}")
print(f"Coeficiente de Determinação (R²): {r2:.2f}")

"""O modelo apresentou um desvio médio de 20 kg, o que, considerando a amostra pequena, demonstra uma tendência de acerto interessante.

O baixo valor de $R²$ indica que apenas os exercícios físicos não são suficientes para prever o peso com precisão; outros fatores como altura, dieta e genética (não presentes no dataset) são fundamentais.

Para fechar com chave de ouro essa parte técnica, vamos comparar o Peso Real vs. o Peso Predito pelo nosso modelo:
"""

plt.figure(figsize=(6, 4))
plt.scatter(y_test, y_pred, color='blue', edgecolors='k')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Peso Real')
plt.ylabel('Peso Predito pelo Modelo')
plt.title('Comparação: Real vs. Predição')
plt.show()

"""O modelo de Regressão Linear apresentou um MAE de 20.60. Em um conjunto de dados com apenas 20 amostras, esse resultado é esperado e demonstra as limitações de modelos simples em bases de dados pequenas. No entanto, o projeto cumpre o papel de estabelecer um ponto de partida e validar o fluxo de dados desde a extração até a predição."""